frameworkVersion: '3'

service: media-optimizer

plugins:
  - serverless-esbuild

custom:
  esbuild:
    exclude:
      - '@aws-sdk/client-s3'
      - sharp

provider:
  name: aws
  region: ap-northeast-2
  stage: production
  runtime: nodejs18.x
  deploymentMethod: direct
  httpApi:
    disableDefaultEndpoint: true
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:DeleteObject'
          Resource:
            - 'arn:aws:s3:::penxle-uploads/*'
        - Effect: Allow
          Action:
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::penxle-data/*'

functions:
  handler:
    handler: ./src/handler.handler
    timeout: 29
    memorySize: 10240
    ephemeralStorageSize: 10240
    layers:
      - !Ref SharpLambdaLayer
    events:
      - httpApi:
          method: GET
          path: /{path+}

layers:
  sharp:
    name: sharp
    path: .lambda/sharp-layer
    compatibleRuntimes:
      - nodejs18.x
    compatibleArchitectures:
      - x86_64
