name: CD

on:
  push:
    branches: [main]

env:
  TURBO_TEAM: penxle
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  production:
    name: Production
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          [literoom, penxle.com, penxle.io, help.penxle.com, landing.penxle.com]
    concurrency: ${{ matrix.project }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare local actions
        run: pnpm run build:actions

      - name: Build local dependencies
        run: pnpm run build:deps

      - uses: dopplerhq/secrets-fetch-action@v1.1.2
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          doppler-project: penxle
          doppler-config: prod
          inject-env-vars: true

      - name: Build project
        run: pnpm exec turbo run build --filter=${{ matrix.project }}

      - name: Upload lambda function
        uses: ./actions/upload-lambda
        with:
          project: ${{ matrix.project }}
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Pulumi
        uses: pulumi/actions@v4

      - name: Deploy infrastructure
        run: |
          cd infra/${{ matrix.project }}
          pulumi stack select penxle/production || pulumi stack init penxle/production
          pulumi config set aws:defaultTags '{"tags":{"ManagedBy":"Pulumi"}}'
          pulumi up --skip-preview --stack penxle/production
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
