name: Preview

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  deploy:
    name: ${{ matrix.app }}
    runs-on: node18/arm64
    if: (github.event.action == 'labeled' && github.event.label.name == 'preview') || (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'preview'))
    strategy:
      fail-fast: false
      matrix:
        app:
          - penxle.com
          - penxle.io
          - help.penxle.com
          - landing.penxle.com
    concurrency:
      group: pr-${{ github.event.pull_request.number }}/${{ matrix.app }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache pnpm store
        uses: ./apps/actions-cache
        with:
          path: /pnpm-store
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup doppler project
        run: doppler setup --no-interactive
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          DOPPLER_CONFIG: preview

      - name: Build app
        run: doppler run -- pnpm exec turbo run build
        working-directory: apps/${{ matrix.app }}
        env:
          TURBO_TEAM: penxle
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          PUBLIC_PULUMI_STACK: pr-${{ github.event.pull_request.number }}

      - name: Upload lambda function
        uses: ./packages/lambda
        with:
          app: ${{ matrix.app }}
          stack: pr-${{ github.event.pull_request.number }}

      - name: Deploy infrastructure
        working-directory: apps/${{ matrix.app }}
        run: |
          pulumi stack init $STACK || true
          pulumi config cp --stack penxle/prod --dest $STACK
          pulumi config set --stack $STACK --path 'aws:defaultTags.tags["pulumi.penxle.io/stack"]' pr-${{ github.event.pull_request.number }}
          pulumi up --skip-preview --stack $STACK
        env:
          STACK: penxle/pr-${{ github.event.pull_request.number }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
