name: Teardown

on:
  pull_request:
    types: [unlabeled]

permissions:
  contents: read
  id-token: write

jobs:
  teardown:
    name: ${{ matrix.app }}
    runs-on: ubuntu-latest
    if: github.event.label.name == 'preview'

    strategy:
      fail-fast: false
      matrix:
        app:
          - penxle.com
          - penxle.io
          - help.penxle.com

    concurrency:
      group: pr-${{ github.event.pull_request.number }}/${{ matrix.app }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::721144421085:role/actions@github
          aws-region: ap-northeast-2

      - name: Connect tailnet
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:github-actions

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name penxle

      - name: Destroy infrastructure
        uses: pulumi/actions@v4
        with:
          command: destroy
          work-dir: apps/${{ matrix.app }}
          stack-name: penxle/pr-${{ github.event.pull_request.number }}
          remove: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_K8S_ENABLE_PATCH_FORCE: 'true'
