name: Teardown

on:
  pull_request:
    types: [unlabeled]

jobs:
  teardown:
    name: ${{ matrix.app }}
    runs-on: ubuntu-latest
    if: github.event.label.name == 'preview'
    strategy:
      fail-fast: false
      matrix:
        app:
          - penxle.com
          - penxle.io
          - help.penxle.com
          - landing.penxle.com
    concurrency:
      group: pr-${{ github.event.pull_request.number }}/${{ matrix.app }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pulumi
        uses: pulumi/actions@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Destroy infrastructure
        run: |
          cd apps/${{ matrix.app }}
          pulumi config refresh --force --stack $STACK
          pulumi destroy --skip-preview --stack $STACK
          pulumi stack rm --yes --stack $STACK
        env:
          STACK: penxle/pr-${{ github.event.pull_request.number }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
