name: CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  bundle:
    name: Bundle
    runs-on: [self-hosted, linux, arm64]
    strategy:
      fail-fast: false
      matrix:
        project: [gh-app, literoom]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare local actions
        run: pnpm run build:actions

      - name: Build project
        run: pnpm exec turbo run build --filter=${{ matrix.project }}

      - name: Bundle lambda function
        uses: ./actions/bundle-lambda
        with:
          project: ${{ matrix.project }}
