name: CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  bundle:
    name: Bundle
    runs-on: linux/arm64
    strategy:
      fail-fast: false
      matrix:
        project: [gh-app, literoom]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup workspace
        uses: ./actions/setup-workspace

      - name: Bundle lambda function
        uses: ./actions/bundle-lambda
        with:
          project: ${{ matrix.project }}
