name: CI

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, linux, arm64]
    strategy:
      fail-fast: false
      matrix:
        linter: [eslint, prettier, spellcheck, svelte, syncpack, typecheck]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare local actions
        run: pnpm run build:actions

      - name: Build local dependencies
        run: pnpm run build:deps

      - name: Run code generation
        run: pnpm exec turbo run codegen

      - name: Run lint
        run: pnpm run lint:${{ matrix.linter }}
