name: CI

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  lint:
    name: Lint
    runs-on: linux/arm64
    strategy:
      fail-fast: false
      matrix:
        linter: [eslint, prettier, spellcheck, svelte, syncpack, typecheck]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup workspace
        uses: ./actions/setup-workspace

      - name: Build dependencies
        run: pnpm run build:deps

      - name: Run code generation
        run: pnpm exec turbo run codegen

      - name: Run lint
        run: pnpm run lint:${{ matrix.linter }}
