name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: [self-hosted, linux, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare local actions
        run: pnpm run build:actions

      - name: Cache test
        uses: ./actions/cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-test-${{ hashFiles('**/pnpm-lock.yaml') }}
